name: Flutter Build AAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build App Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Flutter Cache
        run: rm -rf $HOME/.flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.4" # Set a specific version
          cache: true

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Static Analysis
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build Release AAB
        run: flutter build appbundle --release

      - name: Upload App Bundle as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
