name: Flutter Build AAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build App Bundle
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Flutter Cache
        run: rm -rf $HOME/.flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.6.1"
          cache: true

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Static Analysis
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build Release AAB
        run: flutter build appbundle --release

      - name: Upload App Bundle as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
